public enum ErrorCode : UInt16
{
    None = 0,
    GetVersionDataFailRedis = 1,
    GetVersionDataFailException = 2,

    CreateAccountFailDuplicate = 1001,
    CreateAccountFailException = 1002,
    CreateBasicDataFailInsertItem = 1003,
    CreateBasicDataFailException = 1004,

    LoginFailUserNotExist = 2001,
    LoginFailPwNotMatch = 2002,
    LoginFailCreateUserData = 2003,
    LoginFailGameDataNotMatch = 2004,
    VerifyAccountFailException = 2005,
    VerifyVersionDataFailNoData = 2006,
    VerifyVersionDataFailException = 2007,
    CreateUserDataFailException = 2008,
    NotificationLoadingFailNoUrl = 2009,
    NotificationLoadingFailGetImageFromUrl = 2010,
    NotificationLoadingFailException = 2011,

    InsertItemFailException = 3001,
    DeleteItemFailException = 3002,
    DeleteItemFailWrongData = 3003,
    UserDataLoadingFailException = 3004,
    UserItemLoadingFailException = 3005,

    EmptyRequestHttpBody = 4001,
    InvalidRequestHttpBody = 4002,
    CheckUserGameDataNotMatch = 4003,
    UserNotRegisted = 4004,
    AuthTokenFailWrongAuthToken = 4005,
    AuthTokenFailSetNx = 4006,
    SetJsonFailException = 4007,

    LoadMailDataFailWrongPage = 5001,
    LoadMailDataFailNoData = 5002,
    LoadMailDataFailException = 5003,
    ReadMailFailWrongData = 5004,
    ReadMailFailException = 5005,
    ReceiveMailItemFailWrongData = 5006,
    ReceiveMailItemFailAlreadyGet = 5007,
    ReceiveMailItemFailInsertItem = 5008,
    ReceiveMailItemFailException = 5009,
    DeleteMailFailWrongData = 5010,
    DeleteMailFailException = 5011,

    LoadAttendanceDataFailWrongData = 6001,
    LoadAttendanceDataFailSendMail = 6002,
    LoadAttendanceDataFailException = 6003,
    SendMailAttendanceRewardFailException = 6004,

    PurchaseInAppProductFailDuplicate = 7001,
    PurchaseInAppProductFailException = 7002,
    SendMailInAppProductFailException = 7003,

    EnhanceItemFailWrongData = 8001,
    EnhanceItemFailNotEnhanceable = 8002,
    EnhanceItemFailAlreadyMax = 8003,
    EnhanceItemFailNotEnoughMoney = 8004,
    EnhanceItemFailException = 8005,

    LoadLoadStageListFailException = 9001,
    SelectStageFailNotQualified = 9002,
    SelectStageFailException = 9003,
    CreateStageProgressDataFailAlreadyIn = 9004,
    CreateStageProgressDataFailRedis = 9005,
    CreateStageProgressDataFailException = 9006,
    DeleteStageProgressDataFailRedis = 9007,
    DeleteStageProgressDataFailException = 9008,
    ObtainItemFailWrongItem = 9009,
    ObtainItemFailWrongData = 9010,
    ObtainItemFailRedis = 9011,
    ObtainItemFailException = 9012,
    KillEnemyFailWrongEnemy = 9013,
    KillEnemyFailWrongData = 9014,
    KillEnemyFailRedis = 9015,
    KillEnemyFailException = 9016,
    CheckStageClearFailWrongData = 9017,
    CheckStageClearFailException = 9018,
    GetStageClearRewardFailInsertItem = 9019,
    GetStageClearRewardFailException = 9020

    
}