public enum ErrorCode : UInt16
{
    None = 0,
    GetVersionDataFailRedis = 1,
    GetVersionDataFailException = 2,
    RedisInitFailException = 3,
    MasterDbInitFailException = 4,

    CreateAccountFailDuplicate = 1001,
    CreateAccountFailException = 1002,
    CreateBasicDataFailInsertItem = 1003,
    CreateBasicDataFailException = 1004,

    LoginFailUserNotExist = 2001,
    LoginFailPwNotMatch = 2002,
    VerifyAccountFailException = 2003,
    VerifyVersionDataFailVersionNotMatch = 2004,
    VerifyVersionDataFailException = 2005,
    CreateUserAuthFailRedis = 2006,
    CreateUserAuthFailException = 2007,
    LoadNotificationFailNoUrl = 2008,
    LoadNotificationFailGetImageFromUrl = 2009,
    LoadNotificationFailException = 2010,

    InsertItemFailException = 3001,
    DeleteItemFailException = 3002,
    DeleteItemFailWrongData = 3003,
    UserDataLoadingFailException = 3004,
    UserItemLoadingFailException = 3005,

    EmptyRequestHttpBody = 4001,
    InvalidRequestHttpBody = 4002,
    CheckUserGameDataNotMatch = 4003,
    UserNotRegisted = 4004,
    AuthTokenFailWrongAuthToken = 4005,
    AuthTokenFailSetNx = 4006,
    SetJsonFailException = 4007,

    LoadMailDataFailWrongPage = 5001,
    LoadMailDataFailNoData = 5002,
    LoadMailDataFailException = 5003,
    ReadMailFailWrongData = 5004,
    ReadMailFailException = 5005,
    ReceiveMailItemFailWrongData = 5006,
    ReceiveMailItemFailAlreadyGet = 5007,
    ReceiveMailItemFailInsertItem = 5008,
    ReceiveMailItemFailException = 5009,
    DeleteMailFailWrongData = 5010,
    DeleteMailFailException = 5011,
    InsertItemIntoMailFailException = 5012,

    LoadAttendanceDataFailWrongUser = 6001,
    LoadAttendanceDataFailSendMail = 6002,
    LoadAttendanceDataFailException = 6003,
    HandleNewAttendanceFailWrongUser = 6004,
    HandleNewAttendanceFailNotNewAttendance = 6005,
    HandleNewAttendanceFailSendMail = 6006,
    HandleNewAttendanceFailException = 6007,
    SendMailAttendanceRewardFailAlreadyAttend = 6008,
    SendMailAttendanceRewardFailInsertItemIntoMail = 6009,
    SendMailAttendanceRewardFailException = 6010,

    PurchaseInAppProductFailDuplicate = 7001,
    PurchaseInAppProductFailException = 7002,
    SendMailInAppProductFailException = 7003,

    CheckEnhanceableFailWrongData = 8001,
    CheckEnhanceableFailNotEnhanceable = 8002,
    CheckEnhanceableFailAlreadyMax = 8003,
    CheckEnhanceableFailNotEnoughMoney = 8004,
    CheckEnhanceableFailException = 8005,
    HandleSuccessfulEnhancementFailException = 8006,
    HandleFailedEnhancementFailException = 8007,
    EnhanceItemFailException = 8008,

    LoadLoadStageListFailException = 9001,
    SelectStageFailNotQualified = 9002,
    SelectStageFailWrongStage = 9003,
    SelectStageFailException = 9004,
    CreateStageProgressDataFailAlreadyIn = 9005,
    CreateStageProgressDataFailRedis = 9006,
    CreateStageProgressDataFailException = 9007,
    DeleteStageProgressDataFailRedis = 9008,
    DeleteStageProgressDataFailException = 9009,
    ObtainItemFailWrongKey = 9010,
    ObtainItemFailWrongItem = 9011,
    ObtainItemFailToManyItem = 9012,
    ObtainItemFailRedis = 9013,
    ObtainItemFailException = 9014,
    KillEnemyFailWrongEnemy = 9015,
    KillEnemyFailWrongKey = 9016,
    killEnemyFailToManyEnemy = 9017,
    KillEnemyFailRedis = 9018,
    KillEnemyFailException = 9019,
    CheckStageClearDataFailWrongKey = 9020,
    CheckStageClearDataFailWrongStage = 9021,
    CheckStageClearDataFailWrongData = 9022,
    CheckStageClearDataFailException = 9023,
    ReceiveItemRewardFailInsertItem = 9024,
    ReceiveItemRewardFailException = 9025,
    ReceiveExpRewardFailException = 9026,
    ReceiveStageClearRewardFailException = 9027,
    UpdateStageClearDataFailException = 9028,

    EnterChatLobbyFromLoginFailLobbyFull = 10001,
    EnterChatLobbyFromLoginFailRedis = 10002,
    EnterChatLobbyFromLoginFailException = 10003,
    SelectChatLobbyFailWrongUser = 10004,
    SelectChatLobbyFailAlreadyIn = 10005,
    SelectChatLobbyFailLobbyFull = 10006,
    SelectChatLobbyFailRedis = 10007,
    SelectChatLobbyFailException = 10008,
    SendChatFailWrongUser = 10009,
    SendChatFailRedis = 10010,
    SendChatFailException = 10011,
    ReceiveChatFailWrongUser = 10012,
    ReceiveChatFailException = 10013
}